version: 2
jobs:
  build-test-web:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/premkamalosipalli/web
    resource_class: xlarge
    steps:
      - checkout:
          path: /home/circleci/premkamalosipalli/web
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: npm install
      - run: npm run build
      - run:
          name: Install awscli
          command: |
            sudo apt update
            sudo apt install python3-venv python3-pip
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli
      - run:
          name: Build and push Docker image
          command: |
            eval "docker build -f ./Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM . "
      - run:
          name: Push image
          command: |
            . venv/bin/activate
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            eval "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM"

            eval "docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/verity/test/web:latest"

            eval "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:latest"

workflows:
  version: 2
  build_test:
    jobs:
      - build-test-web:
          filters:
            branches:
              only: main


