version: 2
jobs:
  build-test-web:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/premkamalosipalli/web
    resource_class: large
    steps:
      - checkout:
          path: /home/circleci/premkamalosipalli/web
      - setup_remote_docker: {}
      - run: npm install
      - run: npm run build
      - run:
          name: Install awscli
          command: |
            sudo apt update
            sudo apt install -y python3-venv python3-pip
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli
      - run:
          name: Build Docker image
          command: |
            # Build the Docker image and tag it with a unique build tag
            docker build -f ./Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM .
      - run:
          name: Tag and Push Docker image
          command: |
            . venv/bin/activate
            # Login to ECR
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            
            # Push the unique build tag
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM
            
            # Tag the same image with 'latest' and push it
            docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:build-$CIRCLE_BUILD_NUM $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/premkamalosipalli/web:latest

workflows:
  version: 2
  build_test:
    jobs:
      - build-test-web:
          filters:
            branches:
              only: main
